### ISSUE TITLE
Upload to stackage

### ISSUE THREAD

**Issue by naushadh** [abhinav/pinch#19]
Would make it easier to consume for the `stack` lovers.

**Comment by phile314** [comment]
@abhinav Do you mind if I add pinch and language-thrift to stackage? I would add it using my own name as contact person, so the notifications would go to me and it should not cause any work for you.

**Comment by abhinav** [comment]
Sure, go for it!

language-thrift was previously on Stackage but it had to be removed because of a newer megaparsec (https://github.com/abhinav/language-thrift/issues/13). I think https://github.com/abhinav/language-thrift/pull/15 may have made it Stackage worthy again but I never got around to putting it up.

**Comment by abhinav** [comment]
Closing per https://github.com/commercialhaskell/stackage/pull/5814.
