### ISSUE TITLE
Switch to a streaming parser？

### ISSUE THREAD

**Issue by winterland1989** [abhinav/pinch#9]
Recently i am try to implement a pinch transport layer, but I think current Parser API can't support raw transport but only framed one, because in order to decode a message I have to know the length, there is n way to suspend current Message Parser, so I propose replacing current Parser with a streaming one, for example, the Decoder in binary package.

**Comment by abhinav** [comment]
Hello. Yes, a streaming parser is definitely worth looking into; although I would use `cereal` rather than `binary` for this.

**Comment by winterland1989** [comment]
Thanks, I can make a patch. is there anything particular reason you prefer cereal over binary?

**Comment by abhinav** [comment]
Oh, that would be great! Although I haven't had a chance to verify this myself, what I've read is that `cereal` tends to be faster than `binary` because it relies on strict ByteStrings. See https://www.fpcomplete.com/blog/2016/03/efficient-binary-serialization, for example.

Granted that cereal and binary are a

**Comment by naushadh** [comment]
Found a more extensive benchmark with libraries beyond `cereal` and `binary`.
https://github.com/haskell-perf/serialization

**Comment by phile314** [comment]
I created a PR porting pinch to cereal: https://github.com/abhinav/pinch/pull/28

**Comment by phile314** [comment]
Landed in master.
